require "bundler/gem_tasks"

require 'rake'
require 'rspec/core/rake_task'
require_relative 'config/environment'

namespace :db do

	desc "create the database"
	task :create do
	  puts "Creating file #{DB_PATH} if it doesn't exist..."
	  touch DB_PATH
	end

	desc "drop the database"
	task :drop do
	  puts "Deleting #{DB_PATH}..."
	  rm_f DB_PATH
	end

	desc "migrate the database (options: VERSION=x, VERBOSE=false, SCOPE=blog)."
	task :migrate do
	  ActiveRecord::Migrator.migrations_paths << File.dirname(__FILE__) + 'db/migrate'
	  ActiveRecord::Migration.verbose = ENV["VERBOSE"] ? ENV["VERBOSE"] == "true" : true
	  ActiveRecord::Migrator.migrate(ActiveRecord::Migrator.migrations_paths, ENV["VERSION"] ? ENV["VERSION"].to_i : nil) do |migration|
	    ENV["SCOPE"].blank? || (ENV["SCOPE"] == migration.scope)
	  end
	end

	desc 'Retrieves the current schema version number'
	task :version do
	  puts "Current version: #{ActiveRecord::Migrator.current_version}"
	end
end

desc 'Start IRB with application environment loaded'
task :console do
  exec "irb -r./config/application"
end

desc "Run the specs"
RSpec::Core::RakeTask.new(:spec)

task :default  => :specs
