require "bundler/gem_tasks"
require 'fileutils'


require 'rake'
require 'rspec/core/rake_task'

desc "seed test files"
task :seed do
	test_str1 = "# <snip>\nclass OrangeTree\n  attr_reader :age, :height\n  def initialize\n    @age = 0\n    @oranges = []\n  end\n#</snip>\n\n# test <snip> TITLE\n  def age!\n    @oranges += Array.new(rand(1..10)) { Orange.new } if @age > 5\n  end\n#</snip>\n\n#   ewre w<snip> test\n  def any_oranges?\n    !@oranges.empty?\n  end\n# test </snip> test\n\n  def pick_an_orange!\n"
	test_str2 = "#<$> Title ggg\ndef method\n  \"code\"\nend\n#</$>\n\n#<$> Title 2323\ndef method\n  \"code\"\nend\n#</$>\n\n#<$> Title 4\ndef method\n  \"code\"\nend\n#</$>"
	test_str3 = "# <snip> Title of first snip\n  desc \"create the database\"\n  task :create do\n    puts \"Creating file \#{DB_PATH} if it doesn't exist...\"\n    touch DB_PATH\n  end\n# </snip>\n\n# <snip> Title of this snip\n  desc \"drop the database\"\n  task :drop do\n    puts \"Deleting \#{DB_PATH}...\"\n    rm_f DB_PATH\n  end\n# </snip>\n\n# <snip> Title of first snip\n  desc \"create the database\"\n  task :create do\n    puts \"Creating file \#{DB_PATH} if it doesn't exist...\"\n    touch DB_PATH\n  end\n# </snip>\n\n# <snip> Title of this snip\n  desc \"drop the database\"\n  task :drop do\n    puts \"Deleting \#{DB_PATH}...\"\n    rm_f DB_PATH\n  end\n# </snip>"
	test_str_js = "//<$> Title ggg\nvar test1 = 44;\nvar test2 = 22;\n//</$>\n\n//<$>\nvar test4 = \"Hola\";\n//</$>\n\n"
  test_str_erb = "<!-- <$> Title ggg -->\n  <% @snips.each do |snip| %>\n  <p><%= snip.title %></p> \n<% end %>\n<!-- </$> --> \n\n<!-- <$> Title ggg -->\n  <% @snips.each do |snip| %>\n  <p><%= snip.title %></p> \n<% end %>\n<!-- </$> --> \n\n"
	test_str_html = "<!-- <$> Title ggg -->\n  <p>Hello world</p>\n  <h1>title</h1> \n<!-- </$> --> \n\n<!-- <$> Title ggg -->\n  <p>Hello world</p>\n  <h1>title</h1> \n<!-- </$> --> \n\n"


	FileUtils.rm_rf('rspec/test_snip_files')
	Dir.mkdir("rspec/test_snip_files")
	Dir.mkdir("rspec/test_snip_files/subfolder")

	File.open("rspec/test_snip_files/test.rb", "w+") do |file|
     file << test_str1
  end
  File.open("rspec/test_snip_files/test2.rb", "w+") do |file|
     file << test_str2
  end
  File.open("rspec/test_snip_files/subfolder/test3.rb", "w+") do |file|
     file << test_str3
  end
  File.open("rspec/test_snip_files/subfolder/test_js.js", "w+") do |file|
     file << test_str_js
  end
  File.open("rspec/test_snip_files/subfolder/test_erb.erb", "w+") do |file|
     file << test_str_erb
  end
  File.open("rspec/test_snip_files/subfolder/test_html.html", "w+") do |file|
     file << test_str_erb
  end
end

desc "Run the specs"
task :specs do
	RSpec::Core::RakeTask.new(:spec)
end

task :default  => :specs
